### ISSUE TITLE
Misarticulations and articulation issues

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#136]
@SachinPawaskarUNO I've created this issue for testing the hand and feet articulations.

I have found an issue with the articulation of Metatarsal 1. It does not have the set up to articulate with the medial (first) cuneiform, which is really its only articulation. Currently, the articulation options for this bone are with the navicular, the cuboid and the intermediate cuneiform, none of which the bone articulates with. 

Metatarsal 3 isn't set to articulate with metatarsal 4

I will try to check hand articulations next.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer This is exactly the kind of feedback I was hoping for. So, Thanks Much.

@clegarde and @emilystreetman, I would really welcome and appreciate if one or both of you have a quick phone call with @CTegtmeyer and identify these erroneous articulations and attach a spreadsheet to this issues with the necessary changes. I'm hopeful we can get this accomplished by EOD Friday, so that I can push a new update over the weekend.

Once again, Thank you all for your efforts in getting us towards production rollout.

**Comment by clegarde** [comment]
@CTegtmeyer, since you are actively testing and trying to use these articulations, can you please address these in the spreadsheet that was provided to Sachin in #98 and add any that you have found to be missing? @emilystreetman focused on trying to add missing articulations and did not focus on checking through elements that were already listed with articulations. I think you are tracking much more on this issue and can address it the best.

**Comment by CTegtmeyer** [comment]
@clegarde, Yes! I did not see the spreadsheet prior, so I will add these to the it as soon as I am finished. I am working on the hand articulations now and I will try to finish them before the staff meeting. I leave at 10 (Hawaii time) today and am on leave until the 26th, but if you need to call me to discuss this issue as @SachinPawaskarUNO recommends, I am happy to communicate with you outside of my work hours.

**Comment by SachinPawaskarUNO** [comment]
@clegarde @CTegtmeyer Thank you for getting this coordinated amongst yourself.

@CTegtmeyer can you please add new changes to the bottom of the spreadsheet, also when you add or subtract maybe use a different colored row for additions versus subtractions. Thanks much

**Comment by CTegtmeyer** [comment]
@clegarde @SachinPawaskarUNO 
Here is the updated spreadsheet with hand and feet misarticulations. The additions are in red, subtractions are in blue!

I only did the hands and feet, since that was what I was working on when I caught the first one, so if you would like me to double check the rest of the skeleton that already has articulations I can do that as well.

[19Apr18.CET_updated.xlsx](https://github.com/spawaskar-cora/cora-docs/files/1929276/19Apr18.CET_updated.xlsx)

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer, Thank you for the updated spreadsheet.
YES Please, I would like to take you up on your suggestion of double checking the rest of the articulations

**Comment by CTegtmeyer** [comment]
@clegarde @SachinPawaskarUNO I did not find any other misarticulations in the skeleton. The last spreadsheet I sent should be the most updated one.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer @clegarde In the spreadsheet the first item is **metatarsal   1 | medial cuneiform**. I'm guessing this is the same as **Metatarsal   1 | First (Medial) cuneiform**.

**Comment by emilystreetman** [comment]
@CTegtmeyer If you are OK to close this ticket, will you please also close #98?
