### ISSUE TITLE
DNA - need spot to put inconclusive or unassigned results

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#155]
We had a brief discussion one scrum about how to deal with "inconclusive" or "unassigned" mito results, but I don't think we came to a conclusion. What if we added a checkbox or something to note whether or not we had reportable, inconclusive, or unassigned results? @fedamann @cbrown311 @SachinPawaskarUNO 
![screen shot 2018-05-17 at 9 37 43 pm](https://user-images.githubusercontent.com/7350474/40213485-4e73dcf2-5a1b-11e8-9034-8814105616cf.png)

**Comment by fedamann** [comment]
@clegarde Certainly required input from @SachinPawaskarUNO to figure out the solution.  If I understand we need to have a way to capture "Inconclusive" as a result.  AFDIL results can be 
(1) sequence obtained which currently gets listed as a sequence number, 
(2) sequence obtained, but is too short a read to be assigned to a single sequence number. AFDIL calls these "Unassigned".  I think a BR solves this problem by giving all Unassigned sequences a 0 Sequence Number and then listing the sequences that cannot be excluded from the Unassigned sequence under the Mito Seq. Similar field.  
(3) Inconclusive sequence, which means all attempts to get DNA from the remains have failed.  This should be known by the project leads since its a project mgmt. topic to track

**Comment by clegarde** [comment]
Just briefly discussed today with @SachinPawaskarUNO and @cbrown311 that we should also have "cancelled" on this list as well, so options should include: Reportable, Inconclusive, Unable to Assign, and Cancelled.

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#134

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
