### ISSUE TITLE
Adding projects and availability to see on dashboard

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#161]
@SachinPawaskarUNO I added more projects through CoRA Admin, and when I return to the dashboard they do not show up.

**Comment by SachinPawaskarUNO** [comment]
@fedamann That is probably because you have not associated/assigned any users to the projects that you just created. So just go to the project view/edit screen and click "Add users to project" button. This will take you to the subsequent screen where you can add users to the project.

![image](https://user-images.githubusercontent.com/19599773/40448075-10d623d6-5e9a-11e8-8228-8d8ed6292722.png)

![image](https://user-images.githubusercontent.com/19599773/40448136-429c7fbe-5e9a-11e8-8462-3851ca9414f1.png)

**Comment by fedamann** [comment]
Roger -- user error
