### ISSUE TITLE
Add date of mass comparison chart to DNA profile screen

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#187]
Add date of mass comparison chart to DNA profile screen.  
<img width="481" alt="mcc date" src="https://user-images.githubusercontent.com/33848426/41124199-e73ebd5e-6a3c-11e8-9ce7-53c486c62eda.PNG">

**Comment by nmcelroy** [comment]
Addressed this in SachinPawaskarUNO/cora2#250

**Comment by CTegtmeyer** [comment]
This has been verified. MCC Date is on the DNA profile page.

**Comment by clegarde** [comment]
This date has to be entered in a specific format or you continue to get the following error when you click save:
![error when trying to add mcc date_only accepts specific format](https://user-images.githubusercontent.com/7350474/49769246-0ea07400-fca5-11e8-9f63-81feb99cfbe7.png)

I thought it wasn't working because the "Results Date" field will take the date in multiple formats (Ex: 09/23/18, 9/23/2018, etc.), but "MCC Date" will only accept if it is 2018-09-23. This is not intuitive since results date is not specific, so I thought it wasn't working at first. Could these two date fields work the same? 

This was in coracore.org

**Comment by clegarde** [comment]
I just looked at this again, and it looks like this is just a Safari-CoRA hangup. I looked at this in Chrome, and it looks good. The differences are shown below. Since this is working to operate best in Chrome and Edge, @SachinPawaskarUNO would you like me to close this issue again?

Safari, no date guide/calendar:
![screen shot 2018-12-16 at 10 41 19 am](https://user-images.githubusercontent.com/7350474/50056264-539e2d80-011f-11e9-9fc9-fb04f3ea87cd.png)

Google, date guide/calendar:
![screen shot 2018-12-16 at 10 42 05 am](https://user-images.githubusercontent.com/7350474/50056265-5d279580-011f-11e9-8d2f-55c91802086f.png)

**Comment by SachinPawaskarUNO** [comment]
This has been addressed with the v1.1.1 release
