### ISSUE TITLE
Abiltity to list both left and right measurements for whole mandibles

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#196]
Is it possible to adjust the mandibular measurement page so that when you have a complete mandible you can enter both left and right measurements? Currently, there is just one box for symmetric measurements such as Height and Breadth of the Mandibular Body, but these measurements are taken on both the right and left side (as are Minimum and Maximum Ramus Breadth and Maximum Ramus Height). There is currently no way to enter both sets of measurements.

**Comment by emilystreetman** [comment]
This issue requires some further discussion with @SachinPawaskarUNO . The current mandible measurements are named and numbered _01 through _10. Measurements 2, 3, 6, and 7 are currently listed singly, but should each include a bilateral (left and right) entry.

Current
Man_01 - chin height
Man_02 - height of the mandibular body
Man_03 - breadth of the mandibular body

So, should I act like I'm starting from scratch and renumber the new items, inserting them into the existing list? This will shift most measurements to a different number.
Man_01 - chin height
Man_02 - height (left)
Man_03 - height (right)
Man_04 - breadth (left)
Man_05 - breadth (right)

Or, can we keep the numbered list by adding a new level of designator:
Man_01 - chin height
Man_02.1 - height of the mandibular body
Man_02.2 - height of the mandibular body
Man_03.1 - breadth of the mandibular body
Man_03.2 - breadth of the mandibular body

Finally, (unappealing solution to me) we could just make the existing measurements left and add new right side measurements to the end of the list:
Man_01 - chin height
Man_02 - height of the mandibular body (left)
Man_03 - breadth of the mandibular body (left)
...
Man_11 - height of the mandibular body (right)
Man_12 - breadth of the mandibular body (right)

In any case, if we are integrating with huMAN(id) or some kind of FORDISC, we would want to code to preferentially import the LEFT side measurement, substituting right if left is unavailable. I am also worried about renumbering our items and not matching existing data entry lists.  This issue will also apply to several cranial measurements that should be entered bilaterally: OBB, OBH, and MDH.

FYI I am working from this document:
[Measurements (SEED) 27OCT16.xlsx](https://github.com/spawaskar-cora/cora-docs/files/2149846/Measurements.SEED.27OCT16.xlsx)

**Comment by clegarde** [comment]
I think we should just keep the same number and just have a left and right. I know @SachinPawaskarUNO had some ideas on how to display this on the screen.
Man_02 (Left) - height of the mandibular body
Man_02 (Right) - height of the mandibular body

@emilystreetman, can you please list just the measurement numbers with their description that we need to have a left and right? So that it is clear which need to have both. Thanks!

**Comment by emilystreetman** [comment]
Cra_16 | Cra_16 Orbital Breadth (d-ec) | Laterally sloping distance from dacryon   (d) to ectoconchion (ec).
Cra_17 | Cra_17 Orbital Height | Direct distance between the superior and inferior margins taken   perpendicular to the orbital breadth.
Cra_25 | Cra_25 Mastoid Length | Vertical projection of the mastoid   process below and perpendicular to the eye-car (Frankfort) plane.

Man_02 | Man_02 Height of the Mandibular Body | Direct distance from the alveolar process   to the inferior border of the mandible perpendicular to the base at the level   of the mental foramen.
Man_03 | Man_03 Breadth of the Mandibular Body | Maximum breadth measured in the region of the mental foramen   perpendicular to the long axis of the mandibular body.
Man_06 | Man_06 Minimum Ramus Breadth | Least breadth of the mandibular ramus   measured perpendicular to the height of the ramus.
Man_07 | Man_07 Maximum Ramus Breadth | Distance between the most anterior point on the mandibular ramus and a   line connecting the most posterior point on the condyle and the angle of the   jaw.

**Comment by emilystreetman** [comment]
Update - this functionality has not been integrated into the V1.0.0 cat environment

**Comment by emilystreetman** [comment]
Recommendations to replace the single measurements with the below left and right entries:

*Cranium*
- Cra_16L | Cra_16 Left Orbital Breadth (d-ec) | Laterally sloping distance from dacryon (d) to ectoconchion (ec).
- Cra_16R | Cra_16 Right Orbital Breadth  (d-ec) | Laterally sloping distance from dacryon (d) to ectoconchion (ec).
- Cra_17L | Cra_17 Left Orbital Height | Direct distance between the superior and inferior margins taken perpendicular to the orbital breadth.
- Cra_17R | Cra_17 Right Orbital Height | Direct distance between the superior and inferior margins taken perpendicular to the orbital breadth.
- Cra_25L | Cra_25 Left Mastoid Length | Vertical projection of the mastoid process below and perpendicular to the eye-car (Frankfort) plane.
- Cra_25R | Cra_25 Right Mastoid Length | Vertical projection of the mastoid process below and perpendicular to the eye-car (Frankfort) plane.

*Mandible*
- Man_02L | Man_02 Height of the Left Mandibular Body | Direct distance from the alveolar process to the inferior border of the mandible perpendicular to the base at the level of the mental foramen.
- Man_02R | Man_02 Height of the Right Mandibular Body | Direct distance from the alveolar process to the inferior border of the mandible perpendicular to the base at the level of the mental foramen.
- Man_03L | Man_03 Breadth of the Left Mandibular Body | Maximum breadth measured in the region of the mental foramen perpendicular to the long axis of the mandibular body.
- Man_03R | Man_03 Breadth of the Right Mandibular Body | Maximum breadth measured in the region of the mental foramen perpendicular to the long axis of the mandibular body.
- Man_06L | Man_06 Minimum Left Ramus Breadth | Least breadth of the mandibular ramus measured perpendicular to the height of the ramus.
- Man_06R | Man_06 Minimum Right Ramus Breadth | Least breadth of the mandibular ramus measured perpendicular to the height of the ramus.
- Man_07L | Man_07 Maximum Left Ramus Breadth | Distance between the most anterior point on the mandibular ramus and a line connecting the most posterior point on the condyle and the angle of the jaw.
- Man_07R | Man_07 Maximum Right Ramus Breadth | Distance between the most anterior point on the mandibular ramus and a line connecting the most posterior point on the condyle and the angle of the jaw.

*Team*
@skorps would you be willing to look this over, since you also noted it in the scrum today? Including comments on left vs right notation style?
I am also curious whether you or @CTegtmeyer think Man_08 Ramus Height should also be bilateral. (Sorry for the duplication, Caryn, I just realized I can't save this mostly complete list as a draft comment, so I gotta post it as is and request your recommendation here.)

Quick link to the list of measurements in the help guide: https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/measurements/

**Comment by tlvandeest** [comment]
The cranial and mandibular measurements look good to me. @emilystreetman 
Citation correction needed: The Byrd and Adams measurement numbers (#81A, etc.) listed for the Cervical verts are not present in in the 2003 article or either the 2008 or 2014 book chapters.  I think @clegarde and I discussed this a while ago, but I do not remember where they are listed so this reference can be corrected.

**Comment by clegarde** [comment]
There are a number of Byrd and Adams measurements that were not in any of the publications and only within the definition guide we have at DPAA. We had decided to reference the last update of this - Byrd and Adams 2015. The vert measurements should reference this one as well.

**Comment by tlvandeest** [comment]
@clegarde Thanks, Carrie! I have no changes for the list of right and left measurements. @emilystreetman @skorps

**Comment by emilystreetman** [comment]
This update is not active for mandible measurements (please note Man_05 and Man_06 are also out of order on this screenshot.
![image](https://user-images.githubusercontent.com/34662044/47870336-50511b80-ddd7-11e8-9bcf-ead0ab56c189.png)

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer, @emilystreetman @tlvandeest Please verify this issue.
@fedamann This data issue will have to be verified in PROD once we do the v1.0.0 release.

**Comment by emilystreetman** [comment]
Cervical vertebra 1 and 2 look good. 
![image](https://user-images.githubusercontent.com/34662044/48713163-4734bc80-ebd5-11e8-8e39-68329d02b490.png)
![image](https://user-images.githubusercontent.com/34662044/48713183-4e5bca80-ebd5-11e8-8cf1-dbb86352462c.png)

Mandible looks good.
![image](https://user-images.githubusercontent.com/34662044/48713207-587dc900-ebd5-11e8-8971-ae9dabbdbe23.png)

Mastoid process looks good.
![image](https://user-images.githubusercontent.com/34662044/48713300-89f69480-ebd5-11e8-9325-a49fac322802.png)

The cranium orbit measurements were added, but the old measurements are still present - only Cra_16L and Cra_16R should be present, I believe, with Cra_16 removed (same for _17). Will someone else confirm whether this is right or wrong? There might be a consideration for exporting to FORDISC, but I think a better solution than the current one (fewer human errors) might be to autofill the FORDISC export data with left preferentially? (Mastoid and mandible would require the same consideration for FORDISC export.)

![image](https://user-images.githubusercontent.com/34662044/48712929-9f1ef380-ebd4-11e8-9d93-ca09918fae0c.png)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman This issue has been addressed. Please verify this issue.
@fedamann This data issues will have to be verified in PROD once we do the v1.0.0 release.

**Comment by emilystreetman** [comment]
Cranium and mandible measurements are OK.

Didn't catch this yesterday: The old (non-sided) mastoid length currently follows Cra_22 and should be removed.  Left and right mastoid are OK:
![image](https://user-images.githubusercontent.com/34662044/48794080-868b0800-ecbe-11e8-9499-bbb4b1dd2fba.png)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman The above Cranium data issue (Car_25 Mastoid Length) has also be addressed. Please verify this issue.
@fedamann This data issues will have to be verified in PROD once we do the v1.0.0 release.

**Comment by emilystreetman** [comment]
Looks good!
