### ISSUE TITLE
Bone groupings - verification 

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#254]
Confirm list of specimens for max, man, cranium, and skull.  
@emilystreetman, @CTegtmeyer

**Comment by emilystreetman** [comment]
Related back to
#157 Hierarchical groups for inventory
and
 #116 Generating an articulation report

**Comment by emilystreetman** [comment]
Related back to #162 Articulations for hierarchical groups

**Comment by emilystreetman** [comment]
**OK**
 - Arm, Arm and Shoulder, Leg, Hand, Ribs

**Recommend CoRA to auto-select "middle", otherwise OK**
 - Cervical vertebrae, Thoracic vertebrae, Lumbar vertebrae

**_Problems:_**
**Cranium**
 - cranium is a middle element, but many constituent elements have left and right sides (e.g., parietals, temporals)
 - cranium is a middle element, but individual teeth are left OR right

**Mandible/Maxilla**
- list does not include "mandible" or "maxillae"; possible solution would be to name categories "Maxillary dentition" and "Mandibular dentition" while "maxillae" and "mandible" elements are included in "skull" group
 - mandible is a middle element, but individual teeth are left OR right
 - maxillae have left AND right, but individual teeth are left OR right

**Pelvic girdle**
 - sacrum and coccyx are middle, but os coxa are left AND right

**Thorax**
 - vertebrae are middle, but ribs are left AND right

**Shoulder**
 - should be renamed "Shoulder girdle" to match phrasing of "Pelvic girdle"

**Foot**
 - missing "Proximal pedal phalanx 2"

**Comment by emilystreetman** [comment]
@SachinPawaskarUNO 
Please remove: cranium group, pelvic girdle group, and thorax group
Please rename: Maxillae to "Maxillary dentition" and Mandible to "Mandibular dentition"
Please add Proximal pedal phalanx 2 to Foot

These fixes have been approved by @fedamann

**Comment by emilystreetman** [comment]
Sorry, dev team - @SachinPawaskarUNO and @rpernst - the long comment above was intended as conversation between @CTegtmeyer and me. The actual requests were in the shorter comment with "please remove" etc.  At present, the current changes are requested:

- Please remove "maxilla" from Maxillary dentition group
- Please remove "mandible" from Mandibular dentition group
- Please delete Skull group
- Please remove articulations among teeth - e.g., teeth 1 and 14 do not articulate with each other. Instead, each tooth individually articulates only with the maxilla/mandible (which is removed now from the Bone Group). Analysts will add these articulations by going to the maxilla/mandible element and selecting teeth for articulations instead of auto-populating them in the Add Group page.

I believe that covers everything from the scrum today.

**Comment by emilystreetman** [comment]
These requests are verified as activated in CAT
