### ISSUE TITLE
No image in 'Placeholder' on cranial measurements page

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#259]
The cranium measurements page image "placeholder" has not been linked to a cranial image - these are available now.

![cranium_placeholder](https://user-images.githubusercontent.com/34662044/46029683-bd2b1480-c0b9-11e8-8947-2aa577ec19fd.jpg)

**Comment by emilystreetman** [comment]
I need to upload all other needed images - such as cervical vertebra measurements - before this can be addressed

**Comment by SachinPawaskarUNO** [comment]
@fedamann, I'm confident that there are many more bones (Skeletal Elements) which have missing measurements and/or zone images. I would like to get some eyes on these to identify as many of them as we can. This will allow the DEV team (Nicole/Ryan/Sachin) to do these changes efficiently as part of one commit, instead of revisiting this multiple times.

**Comment by emilystreetman** [comment]
This issue has been fixed - closing ticket and opening new ones regarding additional images and measurements.
