### ISSUE TITLE
Help guide missing measurements

### ISSUE THREAD

**Issue by Rachel-Voss** [spawaskar-cora/cora-docs#268]
In the help guide, there are no directions to obtain measurements for cervical vertebrae 5 through 7.
https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/measurements/#vertebrae

**Comment by emilystreetman** [comment]
- This ticket relates back to #248 (cervical measurements activation) and #259 (measurements and images verification)
- Measurement definitions are missing for C3-C7
However, I believe there are only measurements for C1 and C2, and that the issue here is that C3-C7 measurements page is activated although there are no measurements for those elements - rather than measurement descriptions being missing. The fix for this issue will be part of my recommendations in ticket #259.
I am closing this ticket because this issue is covered in an ongoing ticket.
