### ISSUE TITLE
Mandibular teeth (17-32) should not be allowed to articulate with cranium

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#269]
Tooth 17-32 should only be able to articulate with the mandible, but they can currently articulate with the cranium also. This is related to recently closed ticket #254 .

![image](https://user-images.githubusercontent.com/34662044/46697922-66562c80-cbdb-11e8-8e70-c220304359a3.png)

From Tooth 15, I can select a cranium or a maxilla for articulation (correct). But from a cranium or maxilla, I cannot select a Tooth 15 (incorrect).

![image](https://user-images.githubusercontent.com/34662044/46698724-71aa5780-cbdd-11e8-8ce2-5e39761e81a9.png)

The following are the correct articulations for teeth and the recommended fixes:
- Cranium and maxilla should articulate with tooth 1 - tooth 16 (but not tooth 17-32)
- Tooth 1-16 should articulate with cranium or with maxilla (but not mandible)
- Mandible should articulate with tooth 17 - 32 (but not tooth 1-16)
- Tooth 17-32 should articulate with mandible (but not cranium or maxilla)

If you want to send me an xls with existing articulations/formatting, I will update it with these corrections.

**Comment by emilystreetman** [comment]
For group discussion: 
- Should occluding molars/premolars be allowed to articulate? 
- Should this be allowed only if they also articulate with a maxilla/cranium/mandible? 
- Should two neighboring teeth be allowed to articulate?
@clegarde @veronicak7 @CTegtmeyer @skindsc1 @lfkennedy, as people who have participated in some of the tooth tickets, would you consider weighing in? In the interest of structuring CoRA to be open and useful to other users and institutions, I see the value of allowing such articulations. Personally, I would not likely use such options.

**Comment by lfkennedy** [comment]
fwiw: if there are interproximal wear facets, it may be useful to archaeological research to be able to articulate loose teeth.

However, while I could see some situations where other users/institutions may attempt this without the benefit of having alveolar bone (i.e., if you are going to allow tooth-tooth articulations, it seems like a good idea to allow it regardless of the presence of maxillary/mandibular bone), as a researcher I was often more interested in finding antimeres/pair matches of a sort for loose teeth in order to examine MNI and attempt nonmetric analyses.

![image](https://user-images.githubusercontent.com/35273714/46768593-5bb89780-ccae-11e8-9e0a-2dde9718c793.png)

In the above image, I do not see an option for "Pair Match" and it may be a helpful addition.

Additionally, I do not know if all will appreciate having their profile pic automatically set as 1) a dude and 2) a captain - but this is slightly off topic.

**Comment by clegarde** [comment]
I agree that option should exist for tooth-tooth articulations and any other association deemed possible. These may be things we would use at DPAA, but would be something to make sure it’s applicable for other uses as well (archaeology, thanks @lfkennedy for your outside perspective!).

**Comment by emilystreetman** [comment]
For today - further group discussion in or after the scrum would be helpful so that we can decide on recommendations.

**Comment by emilystreetman** [comment]
@rpernst I think Sachin said this is one of your things:

Following discussion including @fedamann at CoRA Scrum 1NOV18, the below fixes should be made and the remainder of dental articulation discussion will be tabled until the dental module is in dev.

The following are the correct articulations for teeth and the recommended fixes:

    - Cranium and maxilla should articulate with tooth 1 - tooth 16 (but not tooth 17-32)
    - Tooth 1-16 should articulate with cranium or with maxilla (but not mandible)
    - Mandible should articulate with tooth 17 - 32 (but not tooth 1-16)
    - Tooth 17-32 should articulate with mandible (but not cranium or maxilla)

If you want to send me an xls with existing articulations/formatting, I will update it with these corrections.

**Comment by emilystreetman** [comment]
Analyst verifies this issue is resolved
