### ISSUE TITLE
Error when Searching in Cora CAT

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#275]
The Application error is now happening when searching for elements in CoRA-CAT under the USS Oklahoma project.  See image below.  @SachinPawaskarUNO @fedamann

 ![cora search error](https://user-images.githubusercontent.com/35308331/47305899-84b32380-d5f0-11e8-9fd7-7aa54f96c5cd.JPG)

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest  I see that it is the USS Oklahoma project. Can you please add information about what search option and search string you where using when you encountered this issue?

**Comment by tlvandeest** [comment]
@SachinPawaskarUNO I just entered "femur" in the search menu for Bone and this is the error that came up. This also happened when searching for other elements and when transitioning to new pages within CoRA (e.g., when trying to get to the Measurements page for a cranium).

**Comment by tlvandeest** [comment]
@SachinPawaskarUNO @fedamann The application error above is also now happening when trying to get to an element from the search list (e.g., clicking on the link for a femur). This error happened at 0850 when presumably when there would not be a large number of people using the program.

**Comment by SachinPawaskarUNO** [comment]
@fedamann and @tlvandeest, I agree that we need to look at this more closely, even though this is a memory spike issue (See image below), We need to take a look at which operations are causing the memory to spike. Increased memory in production will help but we need to get to root cause of which piece of the code needs to be optimized to alleviate this issue. In order to do that we need to have logging and monitoring capabilities from an operational standpoint which will require us to add these services to the CoRA Ecosystem. We have already planned for these in future task orders. I'm recommending that we not close any of these issues until well after we implement the suggested steps and identify root cause.

![image](https://user-images.githubusercontent.com/19599773/48209256-4c268000-e33a-11e8-95fe-0b43dfbd58aa.png)

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest @fedamann, It can be combination of # of users and types of activities being done. It can even be a single user that runs a report or search that requires more memory than what is allocated. Essentially any activity that can take the memory utilized above the current dyno memory quota threshold.
Please also note that the CAT servers are currently sized at the smallest memory level. @fedamann is aware of this and more memory needs to be allocated to these servers in the future.

**Comment by SachinPawaskarUNO** [comment]
Currently we have limited search results to first 500 records. Some Projects like USS Oklahoma have one accession to which all specimens belong. 
Eventually we need to enhance CoRA to include server side pagination.
