### ISSUE TITLE
Zone errors for zygomatics

### ISSUE THREAD

**Issue by sfuehr** [spawaskar-cora/cora-docs#334]
When trying to add a complete left zygomatic as a new element (even though we don't enter cranial elements this way for the USS OK project, others might), the zone section auto-populates with Zones 10 and 11. If you unclick Zone 11 (right zygomatic), the completeness for the element changes to incomplete. Since the sided bones have their own zone, can the connection between zones and element completeness be removed?

Also on the zone page, can "zygoma" be changed to "zygomatic?"

**Comment by emilystreetman** [comment]
For individual cranial bones, the element is created as a left OR a right. Therefore, the zone of "right zygomatic" shouldn't be possible in Stephanie's example above.

I argue that there should not be any zonation of individual cranial bones, because they each consist of a single zone as indicated by the cranium schema. (And because a 'by zone' search across both crania and individual cranial bones is not possible.)

Related to ticket #324

**Comment by SachinPawaskarUNO** [comment]
@sfuehr to provide all bones from which zones need to be removed.

**Comment by emilystreetman** [comment]
This issue resolved in #342 - no zones are presentfor zygomatics now.
Verified and closing.
