### ISSUE TITLE
Cannot Edit DNA Sample #

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#354]
An incorrect DNA sample # was entered during inventory and cannot be corrected. I would like to be able to fix this.

![github](https://user-images.githubusercontent.com/34662044/51336175-83f02900-1a49-11e9-8616-73165347d7a6.JPG)

**Comment by SachinPawaskarUNO** [comment]
@mei215 and @fedamann, @clegarde had a similar question, but it was via a direct email to me. The DNA Sample Number is currently treated as a special field which goes through a unique check within an accession. This happens when we create a new DNA record, after which the system does not allow any updates to the DNA sample number. The workflow for now should be to delete the DNA record for the sample number in question and create a new record.

**Comment by clegarde** [comment]
The ability to delete will be available for project managers and org admin, correct?

**Comment by SachinPawaskarUNO** [comment]
@clegarde That is correct, Both Specimens and DNA records can be deleted by project managers and org admin.
