### ISSUE TITLE
Project Name Disclosure Bug

### ISSUE THREAD

**Issue by jjlynch2** [spawaskar-cora/cora-docs#404]
I noticed all project names are visible under My Profile -> Projects -> Default Project. This could be an information disclosure problem if CoRA becomes public as it allows anyone to view project names regardless of account privileges.

**Comment by SachinPawaskarUNO** [comment]
@jjlynch2 and @fedamann , Upon investigation and closer look. This is not really a bug, You are seeing projects that belong to your org and also projects that have been made public.
Since we are not using the public projects capabilities right now, I'm going to turn this off for now and we can revisit availability of public projects at a later time. I think this will minimize confusion.

**Comment by jjlynch2** [comment]
@SachinPawaskarUNO Sounds good. That makes sense to me. I didn't know that was even built into CoRA yet!

**Comment by SachinPawaskarUNO** [comment]
@jjlynch2 Please verify

**Comment by jjlynch2** [comment]
@SachinPawaskarUNO Verified
