### ISSUE TITLE
Individuating Enhancement Request

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#48]
Following discussions with @clegarde,

When an element is assigned to a DNA sequence number (e.g, Seq 23) or Individual number (e.g, I-01), can all other elements associated with it (through pair matching, articulation, or refit) automatically be given that same sequence or ID number? Or will that data need to be added manually by the user to each refit, pair match, and articulation?

@SachinPawaskarUNO

**Comment by SachinPawaskarUNO** [comment]
@mei215 and @clegarde I think it is a good idea, but I would like to discuss this in a little more detail with the team so that everyone understands and is on the same page. Doing this change may have unintended consequences from an analysis standpoint from my perspective. Hence I would like to proceed with a little caution. @fedamann we need to discuss this in our next SCRUM meeting.

**Comment by SachinPawaskarUNO** [comment]
@mei215 Please verify

**Comment by mei215** [comment]
@SachinPawaskarUNO. Verified. Use of a business rule where logical groupings can be tracked through a variation on an Individual Number (e.g., .1) before the official I-### is assigned meets my current project needs. I still think a cumulative report of all reports, essentially the Report of Segregation, should be able to be produced at any point during analysis to guide the project lead regarding what work should be assigned next. This would maximize the potential of CORA.
