### ISSUE TITLE
Add accession, provenance 1, and provenance 2 to Advance Specimen Report

### ISSUE THREAD

**Issue by btrnew** [spawaskar-cora/cora-docs#490]
Hello :)

It would be helpful to have accession number, provenance 1, and provenance 2 on the advance specimen report screen so that we can more easily search all specific elements in or analyses that have been conducted on a particular accession/provenance 1/provenance 2 combination. 

![CoRAsearch4](https://user-images.githubusercontent.com/43450732/62078142-98c32b80-b1e7-11e9-9d26-3690a68c7ccc.PNG)

**Comment by SachinPawaskarUNO** [comment]
@btrnew Please verify

**Comment by btrnew** [comment]
@SachinPawaskarUNO I just tried to check in CoRA and it appears our IT issue where nothing on CoRA works is back again. I will verify when utility of the application is restored

**Comment by SachinPawaskarUNO** [comment]
@btrnew Yes, did not realize that you are still experiencing problems accessing CoRA in Hawaii. Please try after access is restored by IT. You may also want to follow up with @CTegtmeyer as she was working closely with IT to resolve this issue.
I'm also copying @fedamann and @drjohnbyrd , so that they are also aware of this access issue in Hawaii.

**Comment by SachinPawaskarUNO** [comment]
This has been completed, see screenshot below.
![image](https://user-images.githubusercontent.com/19599773/81076612-731f2d00-8eb1-11ea-9518-7e4f566849ef.png)
