### ISSUE TITLE
Individual Number is a search option in 2 places, but only works in 1

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#521]
The search dropdown offers the option to search by Skeletal Elements > Individual Number and by DNA > Individual Number. Only the first option returns any results. My example case is Ploesti CIL 2017-310-I-03 (see image)

![image](https://user-images.githubusercontent.com/34662044/63447821-51087c00-c402-11e9-9281-8d9e5e530af7.png)

**Comment by clegarde** [comment]
@emilystreetman, I got results for both with your example (CIL 2017-310-I-03), but you only return results that have been DNA sampled for the DNA -> Individual Number option. I previously suggested (#403) we remove this search option from DNA because I think this could be confusing or lead to someone thinking the I# only includes sampled elements. Just keep the Skeletal Elements -> Individual Number option since it returns ALL elements with that I#.

**Comment by emilystreetman** [comment]
Not sure why it wasn't working before, but it is now, thank you.

 I'll go *second* your #403, I agree.
