### ISSUE TITLE
Refits not always autopopulating for both elements

### ISSUE THREAD

**Issue by Katie-East** [spawaskar-cora/cora-docs#555]
Refits entered for one element are not showing up under the refitted element in peer review.

![refit issue 1](https://user-images.githubusercontent.com/46726506/65716502-e384e680-e064-11e9-9d53-6999f60730dd.PNG)
![refit issue two](https://user-images.githubusercontent.com/46726506/65716503-e41d7d00-e064-11e9-9473-3bf33110c7f9.PNG)

**Comment by clegarde** [comment]
This looks like it might be a problem in the regular specimen area, not just peer-review.
When going to the specimen -> Associations -> refit you get the following:
![Screen Shot 2020-01-01 at 6 44 16 PM](https://user-images.githubusercontent.com/7350474/71648192-f2fc7700-2cc6-11ea-8f2d-a50710091576.png)

When you go to the other specimen, this is what it looks like:
![Screen Shot 2020-01-01 at 6 44 32 PM](https://user-images.githubusercontent.com/7350474/71648195-00196600-2cc7-11ea-98b6-2de6e57cece7.png)

**Comment by clegarde** [comment]
For CIL 2017-310:X-5066A::819, when I clicked Actions -> edit, then "Save" (without making any changes, since the correct element is already selected) it does show below:
![Screen Shot 2020-01-01 at 6 47 02 PM](https://user-images.githubusercontent.com/7350474/71648210-44a50180-2cc7-11ea-8496-186d8b2e1e07.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde @Katie-East Please verify

**Comment by clegarde** [comment]
GTG
