### ISSUE TITLE
Clarification on SE Completeness values

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#6]
@fedamann; When I was putting some constraints on the database I encountered as issue. I remember that we had decided to have the following values for SE completeness {Complete, Incomplete, Partial, Fragmented, N/A}, but I'm seeing that the data contains "Mostly Complete". We need to discuss this and see if we need to add this or stick with what we had originally decided.

**Comment by fedamann** [comment]
@SachinPawaskarUNO the list of options {Complete, Incomplete, Partial, Fragmented, N/A} is still a bit of a problem because it isn't mutually exclusive. A SE can be Complete and Fragmented.  There really should only be two options: Complete and Partial with fragmented being an attribute for some other obj or just deleted.

**Comment by SachinPawaskarUNO** [comment]
This issue is related to #23 and is now addressed.
