### ISSUE TITLE
Too Many Requests Issue

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#62]
After entering between 14-28 entries in quick succession the program gets overwhelmed and comes back with a "too many requests" error, requiring a log out and re-log in to clear the queue (although sometimes this doesn't work). This happens quite often when trying to enter complete hands and feet into the element list. Is there a way to increase the available queue for element input?

[Too Many Requests Error.pdf](https://github.com/spawaskar-cora/cora-docs/files/1786599/Too.Many.Requests.Error.pdf)

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer, I'm curious to know the workflow/screens that you are submitting so quickly. Right now for security reasons the application is throttling user requests, We currently restrict users to 30 post request per minute per user. Do you think you are doing approximately 30 posts per minutes.

Throttling is in place to prevent Denial of Service (DoS) attacks. So the application is not being overwhelmed but is intentionally trying to make sure that someone is not maliciously doing a DoS attack.

We can increase the number of requests allowed per minute per user, but wanted to make sure that this a legitimate use case that most users will do. @fedamann this is something we might need to look at.

@CTegtmeyer, just FYI you can simply copy/paste a screen shot in this comment window (See image below) instead of putting it into a pdf file. Just for future reference, it might save you some time and anyone looking at the ticket can quickly see it without having to download a PDF file.

![image](https://user-images.githubusercontent.com/19599773/37070416-fce71952-217c-11e8-8f08-cbae1967e397.png)

**Comment by CTegtmeyer** [comment]
No, definitely not that many that quickly. I am adding about 2-3 elements/minute under the New Skeletal Elements input page. The system gets overwhelmed after anywhere from 14-28 elements at this speed, and then once the system is available again, it takes less elements each time to overwhelm it again.

But, if you are suggesting it is just a matter of pace, I can attempt to add my elements more slowly too see if this fixes the issue. Right now to test the system we are copying previously done inventories, so I think they go a bit quicker than if we were doing an inventory from scratch, a slower input speed might better reflect a real-life situation.

**Comment by CTegtmeyer** [comment]
I have attempted to enter entries much slower and have taken short breaks in between entries to better simulate a situation where we'd be completing an inventory from scratch and the system is still getting overwhelmed after about 25-30 entries at this speed.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer In the next release of CoRA, I'm going to increase the the number of requests allowed. I'll Let you know when I do that. 
@fedamann, This is something we need to keep an eye on. For now I'm going to increase the number of requests allowed per minute/per user and see if that addresses the issue If not then there might be a bug or something else that we might have to look into.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer This issue has been addressed with a new release. I have increased the throttling parameter to handle more number of requests. Hopefully this should alleviate the issue you were seeing earlier. Please verify and close issue.

**Comment by CTegtmeyer** [comment]
@SachinPawaskarUNO I ran into the problem today when attempting to put in elements and queries into CoRA. It was a combinations of search queries and new sample requests. It seems as though it handled the requests better but it still has the same issue.

**Comment by CTegtmeyer** [comment]
@SachinPawaskarUNO  This issue appears to have been fixed. I have not gotten this error with the most recent releases of CoRA. I will close the issue, but monitor it, just in case.
