### ISSUE TITLE
Ability to put letters in the designator line

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#66]
Would it be possible to make it so that the designator can have letters as well as numbers? Since the designator can only be a number it prevents previously DNA sampled elements from being entered into CoRa (these have designators such as 01A)

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer  I'm Ok with making the change.
However I would like to make sure others are on board as well mainly because my current understanding was that Designators should be numbers with each 20X, 30X with each hundred having a meaning for a specific family of bones/skeletal elements.

@fedamann, I think you and the Anthropologists need to make the call because we have had several discussions on the Accession Number, Provenance1, Provenance2 and Designator fields and had come to the conclusion that Designators should be numbers with each 20X, 30X, etc having specific meanings. Maybe @cbrown311  can add to this conversation as well.

**Comment by cbrown311** [comment]
This is another one of those issues that is cropping up because we designed to fit the Oklahoma and OK uses the hundreds numbering convention.   @CTegtmeyer is correct, other projects may need to have letters in addition to numbers since they use the DNA sample as the designator.

**Comment by SachinPawaskarUNO** [comment]
@cbrown311, Thanks for your input.
Given that, @fedamann, I think I would recommend that we implement the change @CTegtmeyer has suggested in the next release. 
I'm recommending that we go with alphanumeric (meaning a-zA-Z0-9), no spaces. Let me know if that will work for all.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer This issue has been addressed with a new release. Please verify and close issue.
