### ISSUE TITLE
Bug When Searching by Individual Number

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#662]
In CoRA production environment, when I search in Ploesti project by "Individual Number" I am receiving incorrect results.

For example, if I search for "Seq 5" in the Individual Number field, because I want to see all elements currently associated with Seq 5, it returns not only elements from Seq 5, but all elements from Seq 50, Seq 51, Seq 52, Seq 53, Seq 54, Seq 55, Seq 56, Seq 57, Seq 58, and Seq 59.  Essentially, it is providing inclusive results instead of exclusive results for the number "5."

**Comment by clegarde** [comment]
An unintended consequence of asking to open up this search to pull in Individual numbers with the ".1" at the end. We have the "Specimens by Individual Number" report, but it does not pull in the same columns as the Search by Individual Number. 
Is it possible to make the search by Individual Number exact but include any ".1". So that if searched "CIL 2003-116-I-10", it would only return "CIL 2003-116-I-10" or "CIL 2003-116-I-10.1" but NOT "CIL 2003-116-I-10", "CIL 2003-116-I-10.1", "CIL 2003-116-I-100", "CIL 2003-116-I-100.1", "CIL 2003-116-I-100.2", etc.?

**Comment by SachinPawaskarUNO** [comment]
@mei215, @clegarde has rightly pointed out that this issue was introduced when we added the ".1" capability to individual search. I will explore options on how we can address both the issues of ".1" search as well as not bringing in "50", "51", etc when searching for "5".

**Comment by SachinPawaskarUNO** [comment]
@mei215 and @clegarde The fix for this has been deployed to PROD, Please verify your respective use cases and close if verified.

**Comment by mei215** [comment]
looks good, thanks! verified and closed
