### ISSUE TITLE
Increase range search for methods with composite scores to +/- 3

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#79]
When searching for similar age estimates for methods that have composite scores, increase range option to +/- 3 in order to account for fluctuation in scoring of multiple features.  For example, in Nawrocki 1998, there are 27 sutures to be scored, each with a potential score from 0 to 3, so the room for error is much greater than when a single epiphysis is scored with 5 stages as in McKern and Stewart 1957.  This is similar to what we do when accounting for measurement error:  measurements under 200 mm get +/- 2 mm error while those above 300 mm get +/3 mm error allowance.

Thoughts? @fedamann @clegarde @mei215 @emilystreetman @Lariabeth @sfuehr @skindsc1

**Comment by skindsc1** [comment]
@cbrown311 I think that makes sense.  +/- 3 should definitely cover any differences in scoring the pubic symphysis.

**Comment by emilystreetman** [comment]
Verified as fixed for: 

- Buckberry and Chamberlain 2002
- McKern and Stewart 1957 Pubic Symphysis
- Falys and Prangle
- both Meindl and Lovejoy 1985 composites
- both Nawrocki 1998 composites
- Hefner and Ousley 2014 OSSA sum

Possible new ticket - not all scores for all methods require this broad range option, but since this issue is fixed, I will close this ticket. (If anyone writes a new ticket to pare down which scores get a broad range, Sachin will probably want it linked back to this one.)
