### ISSUE TITLE
Option for "Go back to search results" after clicking on a sample number

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#81]
Instead of having to click on the "Back" button multiple times, can there be an option/button to go back to the search results?

**Comment by SachinPawaskarUNO** [comment]
@nyukyi Ideally you should use the browser feature, where you can have 2 options. Since we have a workaround for now, I'm not planning on prioritizing this, We can discuss this further in our SCRUM meeting.

1. Hold the click on the browser back button and a history of previous links should appear, from which you can choose to go back to the search page.
2. When opening a link from the search screen, use right mouse click and open link in a new tab or window.
