### ISSUE TITLE
Inquiry: Decimals and Articulated elements

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#86]
This is more of an inquiry than an issue, I hope that is okay.

I noticed with the last update the ability we are now able to put letters in the designator field, which is great, but we lost the ability to use decimals. We (in the Tarawa project) have been using decimals to designate articulating elements (so our hands and feet all share the same number, with a decimal to designate a new element, e,.g. 500.1 calcaneus, 500.2 talus, etc.). Is the removal of the ability to use decimals intentional, or a side effect of the new update, and if it is intentional, we were curious how other projects were putting articulated hands and feet into CoRA... if they were using new number designators for each element and just using the articulation feature within the program to signify articulating elements.

Thanks for you help!

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer We typically want to avoid special characters in fields. For now the field is alphanumeric and hence only allows [a-z,A-Z0-9]. It is no longer treated as a number field, hence no decimals. 
You should now be able to go away from this nomenclature for the Tarawa project because you will be able to generate reports easily for articulations and hence do not need to do that anymore. 

So, YES your observation is correct that CoRA allows you to easily create association between Skeletal Elements for articulations, pair matching, refits and also provides reports to easily get these associated Skeletal Elements.

So for Tarawa, I would recommend not putting the decimal information and just use CoRA to create the appropriate articulation association. This will also eventually help in the overall analysis of your data once all Skeletal Elements have been inventoried.

@fedamann, @cbrown311 Feel free to chime in.

**Comment by CTegtmeyer** [comment]
@SachinPawaskarUNO Then that brings up a few follow up questions.  First, is that there is currently no way to associate/articulate phalanges and sesamoids with any elements. When you try, there is an error message (see attached).  Is there a way to make this feature available?

![capture](https://user-images.githubusercontent.com/36896992/38329551-a69dc816-383d-11e8-8f6a-bddfb0fea6dd.PNG)

Also, is there a way to then recall all of the elements that articulate to each other? (example: an articulated foot).  I just want to pull that foot (and all its elements) out of the inventory. Is there a way to select all of the articulating elements? Currently, there is no way to identify an entire articulated foot or hand, just articulating tarsals/metatarsals and carpals/metacarpals with their nearest articulating element. Is it possible to create a complete hand or foot within the program through articulations and pull that out of the system?
 
Our overall goal is to show that one hand or foot is articulating, and what elements are included in that hand or foot.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer That really helps. I have identified the issue. This was a tough one to debug.
We have some bones that are designated as being articulated, but we do not have information for these in the articulation table as to which other bones it is articulated to. That is why you are getting this error.
@fedamann, @cbrown311 we need to address this ASAP, it seems that the original list of all articulated bones is incomplete. This may have to do with the fact that on the USS Oklahoma project we did not capture any hand and foot articulations. We need to update the base data to include these going forward.

@CTegtmeyer, I would like to see if you can work with maybe @clegarde on helping us complete this missing base data for articulations. Next week I will talk to @clegarde about what data needs to be captured to accomplish this.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer, I really appreciate you working through/testing and help identify these issues. Much appreciated.

**Comment by SachinPawaskarUNO** [comment]
In the future CoRA will display the message below if base data for articulations has not been setup for a bone.

![image](https://user-images.githubusercontent.com/19599773/38461730-681cd912-3a9d-11e8-8c25-5a5c04828fc7.png)

@fedamann and @CTegtmeyer We need to create a separate issue to get the base data setup for articulations for bones that are currently missing it.

**Comment by clegarde** [comment]
I think this is a good idea. Then we'll know that the system isn't currently set up versus some sort of bug or something.
There are articulations missing because when the list was put together, I think it was done based on what would be "typical" in a commingled project. These are elements that do technically articulate, but these articulations are very uncommon to make in a commingled assemblage without _in situ_ information, so they were overlooked as something to include. I will get someone to check through for anything else like this.

**Comment by CTegtmeyer** [comment]
Hi @SachinPawaskarUNO . What are you looking for from me as far as this issue is concerned? Id like to help as much as I can, but I am unclear as to what I should be doing on it.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer, Since we have created a separate issue for a new articulations report, I think you can now close this issue.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer I would like you to work with @clegarde and @fedamann to pull together the list of base Bone articulations that are missing in CoRA. That is why I have assigned you 3 to this issue.
